#!/usr/bin/env python3
"""Regenerate core/tc_cacert.h - the trust anchors compiled into the client.

    python3 tools/mkca.py breadtoasting.com

Bundling our own roots is the whole point: it means the console's ancient
built-in CA store is irrelevant, because we never ask it anything.
"""
import os, subprocess, sys

host = sys.argv[1] if len(sys.argv) > 1 else "breadtoasting.com"
raw = subprocess.run(
    ["openssl", "s_client", "-connect", f"{host}:443", "-servername", host, "-showcerts"],
    input=b"", capture_output=True).stdout.decode(errors="replace")

certs, cur = [], None
for line in raw.splitlines():
    if "BEGIN CERTIFICATE" in line:
        cur = [line]
    elif cur is not None:
        cur.append(line)
        if "END CERTIFICATE" in line:
            certs.append("\n".join(cur)); cur = None
if not certs:
    sys.exit("no certificates returned")

# the leaf is certs[0]; everything above it is a trust anchor candidate
anchors = certs[1:] or certs
def subj(pem):
    p = subprocess.run(["openssl", "x509", "-noout", "-subject"],
                       input=pem.encode(), capture_output=True)
    return p.stdout.decode().strip().replace("subject=", "")

out = ['/* tc_cacert.h - generated by tools/mkca.py from %s - do not edit.' % host,
       ' *', ' * Trust anchors compiled into the client. Regenerate if the server',
       ' * changes certificate authority, or TLS verification will start failing.',
       ' *']
for pem in anchors:
    out.append(" *   %s" % subj(pem))
out += [' */', '#ifndef TC_CACERT_H_INCLUDED', '#define TC_CACERT_H_INCLUDED', '',
        'static const char tc_cacert_pem[] =']
for pem in anchors:
    for line in pem.splitlines():
        out.append('    "%s\\n"' % line)
out += ['    ;', '', '#endif']
dest = os.path.join(os.path.dirname(__file__), "..", "core", "tc_cacert.h")
open(dest, "w").write("\n".join(out) + "\n")
print("wrote core/tc_cacert.h with %d anchor(s)" % len(anchors))
for pem in anchors:
    print("   ", subj(pem))
