#!/usr/bin/env python3
"""Regenerate core/tc_font.h from a PSF1 console font.
   usage: python3 tools/mkfont.py [/usr/share/consolefonts/Lat15-VGA16.psf.gz]"""
import gzip, sys, os
src = sys.argv[1] if len(sys.argv) > 1 else "/usr/share/consolefonts/Lat15-VGA16.psf.gz"
d = gzip.open(src, 'rb').read()
assert d[0] == 0x36 and d[1] == 0x04, "expected a PSF1 font"
cs, off = d[3], 4
L = ["/* tc_font.h - generated by tools/mkfont.py from %s - do not edit. */" % os.path.basename(src),
     "#ifndef TC_FONT_H_INCLUDED", "#define TC_FONT_H_INCLUDED", "#include <stdint.h>",
     "#define TC_FONT_W 8", "#define TC_FONT_H %d" % cs,
     "#define TC_FONT_FIRST 32", "#define TC_FONT_LAST 126",
     "static const uint8_t tc_font[95][%d] = {" % cs]
for c in range(32, 127):
    g = d[off + c*cs: off + (c+1)*cs]
    ch = chr(c).replace("\\", "\\\\").replace("'", "\\'")
    L.append("  {%s}, /* '%s' */" % (",".join("0x%02x" % b for b in g), ch))
L += ["};", "#endif"]
open(os.path.join(os.path.dirname(__file__), "..", "core", "tc_font.h"), "w").write("\n".join(L) + "\n")
print("wrote core/tc_font.h")
